#!/usr/bin/env bash

echo '\n'
echo '                                                                                                                                                                               dddddddd'
echo 'HHHHHHHHH     HHHHHHHHH                   lllllll lllllll                                                                                                  lllllll             d::::::d'
echo 'H:::::::H     H:::::::H                   l:::::l l:::::l                                                                                                  l:::::l             d::::::d'
echo 'H:::::::H     H:::::::H                   l:::::l l:::::l                                                                                                  l:::::l             d::::::d'
echo 'HH::::::H     H::::::HH                   l:::::l l:::::l                                                                                                  l:::::l             d:::::d '
echo '  H:::::H     H:::::H      eeeeeeeeeeee    l::::l  l::::l    ooooooooooo        wwwwwww           wwwww           wwwwwww ooooooooooo   rrrrr   rrrrrrrrr   l::::l     ddddddddd:::::d '
echo '  H:::::H     H:::::H    ee::::::::::::ee  l::::l  l::::l  oo:::::::::::oo       w:::::w         w:::::w         w:::::woo:::::::::::oo r::::rrr:::::::::r  l::::l   dd::::::::::::::d '
echo '  H::::::HHHHH::::::H   e::::::eeeee:::::eel::::l  l::::l o:::::::::::::::o       w:::::w       w:::::::w       w:::::wo:::::::::::::::or:::::::::::::::::r l::::l  d::::::::::::::::d '
echo '  H:::::::::::::::::H  e::::::e     e:::::el::::l  l::::l o:::::ooooo:::::o        w:::::w     w:::::::::w     w:::::w o:::::ooooo:::::orr::::::rrrrr::::::rl::::l d:::::::ddddd:::::d '
echo '  H:::::::::::::::::H  e:::::::eeeee::::::el::::l  l::::l o::::o     o::::o         w:::::w   w:::::w:::::w   w:::::w  o::::o     o::::o r:::::r     r:::::rl::::l d::::::d    d:::::d '
echo '  H::::::HHHHH::::::H  e:::::::::::::::::e l::::l  l::::l o::::o     o::::o          w:::::w w:::::w w:::::w w:::::w   o::::o     o::::o r:::::r     rrrrrrrl::::l d:::::d     d:::::d '
echo '  H:::::H     H:::::H  e::::::eeeeeeeeeee  l::::l  l::::l o::::o     o::::o           w:::::w:::::w   w:::::w:::::w    o::::o     o::::o r:::::r            l::::l d:::::d     d:::::d '
echo '  H:::::H     H:::::H  e:::::::e           l::::l  l::::l o::::o     o::::o            w:::::::::w     w:::::::::w     o::::o     o::::o r:::::r            l::::l d:::::d     d:::::d '
echo 'HH::::::H     H::::::HHe::::::::e         l::::::ll::::::lo:::::ooooo:::::o             w:::::::w       w:::::::w      o:::::ooooo:::::o r:::::r           l::::::ld::::::ddddd::::::dd'
echo 'H:::::::H     H:::::::H e::::::::eeeeeeee l::::::ll::::::lo:::::::::::::::o              w:::::w         w:::::w       o:::::::::::::::o r:::::r           l::::::l d:::::::::::::::::d'
echo 'H:::::::H     H:::::::H  ee:::::::::::::e l::::::ll::::::l oo:::::::::::oo                w:::w           w:::w         oo:::::::::::oo  r:::::r           l::::::l  d:::::::::ddd::::d'
echo 'HHHHHHHHH     HHHHHHHHH    eeeeeeeeeeeeee llllllllllllllll   ooooooooooo                   www             www            ooooooooooo    rrrrrrr           llllllll   ddddddddd   ddddd'
echo '\n'
