#!/usr/bin/env groovy

pipeline {
    agent any

    environment {
        HELLO_MESSAGE = 'Hello World! from Jenkins'
    }

    stages {

        stage('Hello') {
            steps {
                echo "${env.HELLO_MESSAGE}"
            }
        }

        stage('Build') {
            steps {
                sh 'echo "Building..."'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Testing..."'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying..."'
            }
        }

    }

    post {
        always {
            sh "echo 'Pineline finished'"
        }

        success {
            sh "echo 'Pineline success'"
        }

        failure {
            sh "echo 'Pineline failed'"
        }
    }
}